package com.home.urix.PayRoll.View;

public enum EmployeeEditMenuEnum {
    OPTION_FIRSTNAME,
    OPTION_MIDDLE_NAME,
    OPTION_LASTNAME,
    OPTION_BIRTHDAY,
    OPTION_HIRE_DATE,
    OPTION_SALARY,
    OPTION_POSITION_TYPE,
    OPTION_POSITION_NAME,
    OPTION_SET_MANAGER,
    OPTION_DEPARTMENT,
    OPTION_EXIT;
}
