package com.home.urix.PayRoll.View;

public enum MainMenuEnum {
    OPTION_SPECIFY_FUND,
    OPTION_SHOW_EMPLOYEES_MENU,
    OPTION_DEPARTMENT_MANIPULATION,
    OPTION_BALANCE_ALLOCATION_TYPE,
    OPTION_BALANCE_ALLOCATION_PLACE,
    OPTION_PAYROLL_PRINT,
    OPTION_EXIT;
}
